name: Go-Todo CI/CD Pipeline

on: [push]

jobs:
  tests:
    runs-on: ubuntu-22.04
    container: golang:1.25.7
  
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install dependencies
      run: go mod tidy

    - name: Vet
      run: |
        go vet ./...

    - name: Run local server
      run: |
        CGO_ENABLED=0 GOOS=linux go run cmd/go-todo/main.go &
        sleep 80
        go test ./... -v

  deploy:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-22.04
    needs: tests
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Prepare Docker Tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mascotmascot1/go-todo
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}